spring.application.name=AnimalsOng-Backend

server.port=8081

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

brevo.api.key=${BREVO_API_KEY}
email.from=animals.ongbrasil@gmail.com

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

spring.mongodb.uri=${MONGODB_URI}

frontend.url=${FRONTEND_URL}

jwt.public.pem=/etc/secrets/public.pem
jwt.private.pem=/etc/secrets/private.pem

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB