spring.application.name=AnimalsOng-Backend

server.port=8081

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.password=${MAIL_PASSWORD}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

spring.mongodb.uri=${MONGODB_URI}

frontend.url=${FRONTEND_URL}

jwt.public.pem=/etc/secrets/public.pem
jwt.private.pem=/etc/secrets/private.pem

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB